=== Panda-Lewandowski/DataBase/Lab5/doctors.xsd
<?xml version="1.0" standalone="yes"?>
<xsd:schema id="Doctors" xmlns="" xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
      targetNamespace="urn:MyUri" elementFormDefault="qualified" 
      xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
  <xsd:element name="Doctors" msdata:IsDataSet="true" msdata:Locale="en-US">
    <xsd:complexType>
      <xsd:choice minOccurs="0" maxOccurs="unbounded">
        <xsd:element name="P">
          <xsd:complexType>
            <xsd:attribute name="Passenger" type="xsd:string" />
            <xsd:attribute name="Sex" type="xsd:string" />
            <xsd:attribute name="Age" type="xsd:string" />
          </xsd:complexType>
        </xsd:element>
      </xsd:choice>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== Panda-Lewandowski/DataBase/Lab5/doctors.xml
<Doctors
  xmlns="urn:MyUri"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="urn:MyUri doctors.xsd">
  <P Passenger="Frauenthal Dr. Henry William" Sex="male" Age="50"/>
  <P Passenger="Pain Dr. Alfred" Sex="male" Age="23"/>
  <P Passenger="Stahelin-Maeglin Dr. Max" Sex="male" Age="32"/>
  <P Passenger="Brewe Dr. Arthur Jackson" Sex="male"/>
  <P Passenger="Moraweck Dr. Ernest" Sex="male" Age="54"/>
  <P Passenger="Minahan Dr. William Edward" Sex="male" Age="44"/>
  <P Passenger="Leader Dr. Alice (Farnham)" Sex="female" Age="49"/>
</Doctors>
